stages:
  - release

# Release stage
release:
  stage: release
  script:
    - export http_proxy=172.29.40.97:3999
    - export HTTP_PROXY=172.29.40.97:3999
 #   - export https_proxy=172.29.40.97:3999
    - cd $CI_PROJECT_DIR
    - cp .env.example .env
    - sed -i "s/APP_HOST=.*/APP_HOST=$APP_HOST/g" .env
    - sed -i "s/MINIO_HOST=.*/MINIO_HOST=$MINIO_HOST/g" .env
    - sed -i "s/REDIS_HOST=.*/REDIS_HOST=$REDIS_HOST/g" .env
    - mkdir -p build/certs/{app,nginx,minio,redis}
    - cp /etc/letsencrypt/live/$APP_HOST/* build/certs/app
    - cp /etc/letsencrypt/live/$APP_HOST/* build/certs/nginx
    - cp /etc/letsencrypt/live/$APP_HOST/* build/certs/redis
    - cp /etc/letsencrypt/live/$APP_HOST/privkey.pem build/certs/minio/private.key
    - cp /etc/letsencrypt/live/$APP_HOST/fullchain.pem build/certs/minio/public.crt
    - chmod 755 build/certs/redis/*
    - docker compose down
    - docker compose up -d --build
    - export http_proxy=
    - export https_proxy=
  only:
    - dev