# Services
services:
  # App
  app:
    build:
      context: .
      dockerfile: build/docker/app/Dockerfile
    container_name: app.$APP_HOST
    restart: unless-stopped
    volumes:
      - ./build/certs/app:/etc/ssl/certs:ro
    tty: true
    environment:
      TZ: ${APP_TZ}
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - cdn
  # Minio
  minio:
    image: minio/minio:latest
    container_name: minio.$APP_HOST
    restart: unless-stopped
    command: server /data
    tty: true
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-root}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-myawesomepassword}
      TZ: ${APP_TZ}
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio:/data
    networks:
      - cdn
  # Nginx
  nginx:
    image: nginx:stable-alpine
    container_name: nginx.$APP_HOST
    restart: unless-stopped
    environment:
      TZ: ${APP_TZ}
      SERVER_NAME: ${APP_HOST}
      SERVER_PORT: 8250
      PROXY_PASS: https://app.${APP_HOST}:${APP_PORT}
    tty: true
    depends_on:
      - app
    ports:
      - 8250:8250
    volumes:
      - ./build/certs/nginx:/etc/nginx/certs:ro
      - ./build/docker/nginx:/etc/nginx/templates:ro
    networks:
      - cdn
# Volumes
volumes:
  minio:
# Networks
networks:
  cdn:
    driver: bridge